MIN_MAX_OBJ_SIZE: [0, 1000000000] #131072]
SCORE_THRESHOLD: 0.15
IOU_THRESHOLD: 0.25
MINIMUM_TILE_OVERLAP: 384
EDGE_CASE_MARGIN: 32
PREFER_POLYGONS: True
EXPERIMENTAL_NMS_OPTIMIZATION: True
TIME: True
