name: Sync with Hugging Face Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Sync with Hugging Face
      uses: nateraw/huggingface-sync-action@v0.0.4
      with:
        github_repo_id: asgersvenning/BiodivX-XPRIZE-Localizer
        huggingface_repo_id: asgersvenning/BiodivX-XPRIZE-Localizer
        repo_type: space
        space_sdk: docker
        hf_token: ${{ secrets.HF_TOKEN }}